# version: "3.8"

services:
  user-service:
    build:
      context: ./services/user-service
    ports:
      - "5001:5001"
    env_file:
      - ./services/user-service/.env
    depends_on:
      - mysql
  
  notification-service:
    build:
      context: ./services/notification-service
    ports:
      - "5002:5002"
    env_file:
      - ./services/notification-service/.env
    depends_on:
      - mongodb

  recommendation-service:
    build:
      context: ./services/recommendation-service
    ports:
      - "5003:5003"
    env_file:
      - ./services/recommendation-service/.env
    depends_on:
      mysql:
        condition: service_healthy


  scheduler-service:
    build:
      context: ./services/scheduler-service
    ports:
      - "5004:5004"
    env_file:
      - ./services/scheduler-service/.env
    depends_on:
      - notification-service

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: M@y@nk3331!
      MYSQL_DATABASE: notification_system
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
